### ISSUE TITLE
Config.json StringProfile - New filter fields "holder-pac" and "connector-pac"

### ISSUE THREAD

**Issue by paulBMentopolis** [openBackhaul/Accessport2LtpTranslator#105]
For usage of "holder-pac" and "connector-pac" fields which contain sequence-id, the StringProfile-filters for MWDI calls must be updated.

These StringProfiles need "equipment-augment-1-0:holder-pac" and "equipment-augment-1-0:connector-pac" added in filter:
"atlt-1-0-0-string-p-001"
"atlt-1-0-0-string-p-002"

**Comment by ThomasSeitz** [comment]
Is related to pull request:
https://github.com/openBackhaul/Accessport2LtpTranslator/pull/102  (Issue#72)

**Comment by kmohr-soprasteria** [comment]
closed, will be handled in #72 / #102.
