### ISSUE TITLE
Create ServiceList for A2LT

### ISSUE THREAD

**Issue by ThomasSeitz** [openBackhaul/Accessport2LtpTranslator#21]
First ideas what kind of services could be needed:
- service-name: /v1/translate-equipment-to-ltp

In order to compare planning data and system settings as well as performance data, it should be possible to establish standardised relationships between the SDN models and current planning tools.
The input data for the service should be an so called address.
An Address is the concatenation of the sequence IDs.
All objects in the connector and contained-holder collections of every object in the equipment collection are (will be) identifiable via a sequence ID.

**Comment by kurzkama** [comment]
Comment for Review
