### ISSUE TITLE
Semantic error in the response-body of the paths./v1/translate-equipment-sequence-ids-to-ltp-uuids (items)

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/Accessport2LtpTranslator#70]
In the OAS , in the line 509 , there is a Semantic error at paths./v1/translate-equipment-sequence-ids-to-ltp-uuids.post.responses.200.content.application/json.schema.properties.access-port-to-ltp-mappings. 

**Proposal :**
the keyword "items:" shall be included
![image](https://github.com/openBackhaul/Accessport2LtpTranslator/assets/62344562/de5815d7-0934-4933-b83a-39f3a0a138f2)

**Comment by kmohr-soprasteria** [comment]
keyword will be added in spec v1.0.1
