### ISSUE TITLE
Request body example of the service /v1/translate-equipment-sequence-ids-to-ltp-uuids requires a modification 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/Accessport2LtpTranslator#71]
In the request-body example for the service /v1/translate-equipment-sequence-ids-to-ltp-uuids , the “link-id” needs to be changed to string-of-concatenated-sequence-ids

![image](https://github.com/openBackhaul/Accessport2LtpTranslator/assets/62344562/922ba8e6-7ab9-4ab3-b4a4-493a8dbf191a)

**Comment by kmohr-soprasteria** [comment]
will be changed in oas of v1.0.1 spec

**Comment by ThomasSeitz** [comment]
solved via issue coming from mentopolis in paralell.
