### ISSUE TITLE
Clarification regarding the fields filter to get the sequence-id of the connector and the contained-holder 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/Accessport2LtpTranslator#72]
In the forwardings , 
- ReadingEquipmentDataOfTopLevelElement , 
- ReadingEquipmentDataInHolder 

we are trying to get the sequence-id of the connector and the contained-holder,
by using the following path to MWDI,
 "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mountName}/equipment={uuid}?fields=contained-holder(**occupying-fru;sequence-id**);connector(**local-id;sequence-id**)"

But , the sequence-id resource is not directly available in the contained-holder and connector class , 
and it is available in the 
- **equipment-augment-1-0:holder-pac** in the contained-holder class
```diff
              {
                    "local-id": "123456789",
+                   "equipment-augment-1-0:holder-pac": {
                        "sequence-id": 99
                    },
                    "occupying-fru": "123456789"
                }
```
- **equipment-augment-1-0:connector-pac** in the connector class
```diff
              {
                    "local-id": "1963217440",
+                   "equipment-augment-1-0:connector-pac": {
                        "sequence-id": 3
                    }
                }
```

The filter shall be 

- ?fields=contained-holder(occupying-fru;**equipment-augment-1-0:holder-pac(sequence-id)**) for contained-holder
- ?fields=connector(local-id;**equipment-augment-1-0:connector-pac(sequence-id)**) for connector

So, the filter provided in the OAS and the configuration file shall be changed 
from
contained-holder(occupying-fru;**sequence-id**);connector(local-id;**sequence-id**)
to 
contained-holder(occupying-fru;**equipment-augment-1-0:holder-pac(sequence-id)**);connector(local-id;**equipment-augment-1-0:connector-pac(sequence-id)**)

**Comment by kmohr-soprasteria** [comment]
Needs to be changed in
- profileInstances
- configFile
- Diagram
- OAS

**Comment by ThomasSeitz** [comment]
`Test result:`
PROD SDN-C direct:
http://10.xx.xx.xx:8181/rests/data/network-topology:network-topology/topology=topology-netconf/node=530270098/yang-ext:mount/core-model-1-4:control-construct/equipment=1?fields=contained-holder(occupying-fru;equipment-augment-1-0:holder-pac(sequence-id));connector(local-id;equipment-augment-1-0:connector-pac(sequence-id))


```
{
    "core-model-1-4:equipment": [
        {
            "uuid": "1",
            "contained-holder": [
                {
                    "local-id": "1921261567",
                    "equipment-augment-1-0:holder-pac": {
                        "sequence-id": 1
                    },
                    "occupying-fru": "1921261567"
                },
                {
                    "local-id": "1913126911",
                    "equipment-augment-1-0:holder-pac": {
                        "sequence-id": 99
                    },
                    "occupying-fru": "1913126911"
                },
                {
                    "local-id": "1921257471",
                    "equipment-augment-1-0:holder-pac": {
                        "sequence-id": 0
                    },
                    "occupying-fru": "1921257471"
                },
                {
                    "local-id": "1938034687",
                    "equipment-augment-1-0:holder-pac": {
                        "sequence-id": 0
                    },
                    "occupying-fru": "1938034687"
                },
                {
                    "local-id": "1921265663",
                    "equipment-augment-1-0:holder-pac": {
                        "sequence-id": 2
                    },
                    "occupying-fru": "1921265663"
                },
                {
                    "local-id": "1921269759",
                    "equipment-augment-1-0:holder-pac": {
                        "sequence-id": 3
                    },
                    "occupying-fru": "1921269759"
                },
                {
                    "local-id": "1921273855",
                    "equipment-augment-1-0:holder-pac": {
                        "sequence-id": 4
                    },
                    "occupying-fru": "1921273855"
                }
            ]
        }
    ]
}
```

**Comment by ThomasSeitz** [comment]
First commit on change in oas (yaml)
