### ISSUE TITLE
clarification regarding the forwarding ReadingServerLTP

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/Accessport2LtpTranslator#73]
We are finding the list of [equipment + connector pair] information in the “ReadEquipmentDataInHolder” forwarding.
For example , 
1.	for a string-of-concatenated-sequence-ids  "h1.c3.h4.c1" , 
2.	We many find the following [equipment + connector pair] information in the “ReadEquipmentDataInHolder” forwarding
          [ 
          { equipment-uuid-1 , connector-local-id-1 } ,
          { equipment-uuid-2 , connector-local-id-1 } 
          ]

Kindly please let us know whether this example is correct. 
If so , please clarify the following doubt , 

In the  ReadingServerLTP forwarding , we are performing the forwarding only once and not for all the equipment connector pair.

![image](https://github.com/openBackhaul/Accessport2LtpTranslator/assets/62344562/a48a9ba4-05ef-49a5-bd89-62b515036231)

Kindly please let us know whether “ReadingServerLTP” Step shall be performed for each of the identified equipment , connector pair ?

**Comment by ThomasSeitz** [comment]
Implementer is informed.
