### ISSUE TITLE
UUID parameters with "a2lt" as application-abbreviation are not valid with the current regex

### ISSUE THREAD

**Issue by paulBMentopolis** [openBackhaul/Accessport2LtpTranslator#86]
Example: StringProfile services

Current regex is:
"^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-string-p-([0-9]{3})$"

For example:
/core-model-1-4:control-construct/profile-collection/profile={uuid}/string-profile-1-0:string-profile-pac/string-profile-capability/string-name

Parameter UUID like "a2lt-1-0-0-action-p-000" will not be valid and service request cannot succeed.

This problem concerns all API parameters which contain the application-abbreviation (A2LT).

**Comment by ThomasSeitz** [comment]
Replace 'a2lt' to 'atlt' in all files from spec.
